before:
  hooks:
    - go mod download
builds:
- binary: '{{ .ProjectName }}_v{{.Version}}'
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format: zip
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
